### ISSUE TITLE
libhts with libdeflate: tabix compressed index not byte identical

### ISSUE THREAD

**Issue by mr-c** [samtools/htslib#827] opened 2019-02-20 08:40 UTC
This broke the pysam tests: https://github.com/pysam-developers/pysam/issues/761

**Comment by mr-c** [comment] 2019-02-20 08:51
I get the same result when I build htslib with libdeflate and GCS+S3 turned off. Next to see what happens without libdeflate (did some other dependency induce the change?)

**Comment by mr-c** [comment] 2019-02-20 09:03
Removing libdeflate restores the previous format, so it is indeed the culprit

**Comment by mr-c** [comment] 2019-02-20 09:08
Here's the diff from running `tabix` on https://github.com/pysam-developers/pysam/blob/master/tests/tabix_data/example.gtf.gz

```
6,10c6,10
< 00000050: 6042 1803 17bf c580 0ab8 90d8 1fa5 2074  `B............ t
< 00000060: cc3c 08fd 7219 84d6 dc06 a1fb b7a3 d27f  .<..r...........
< 00000070: 7640 6874 3731 23f9 0366 6fb4 1684 0e81  v@ht71#..fo.....
< 00000080: ba17 c667 6058 c6c7 80e4 5e98 7a98 b830  ...g`X....^.z..0
< 00000090: 032a e041 3613 4a3b 4950 8746 b809 0200  .*.A6.J;IP.F....
---
> 00000050: 6042 3207 267e 8b01 1570 21b1 3f4a 41e8  `B2.&~...p!.?JA.
> 00000060: 9879 10fa e532 08ad b90d 42f7 6f47 a5ff  .y...2....B.oG..
> 00000070: ec40 7523 cc0d cc48 fe80 d91b ad05 a143  .@u#...H.......C
> 00000080: a0ee 85f1 1918 96f1 21bb 17a6 1e26 2e8c  ........!....&..
> 00000090: e65e 1e64 33a1 b493 0475 6884 9b20 0000  .^.d3....uh.. ..
```

(top is from a `tabix` compiled with libdeflate, bottom is without libdeflate)

**Comment by mr-c** [comment] 2019-02-20 09:12
However, comparing the `gunzip`'d output confirms that the indexes themselves are the same. Maybe a note should be added to the docs about this?

**Comment by mp15** [comment] 2019-02-20 09:17
Using libdeflate changes the compressed file itself yes? Still same decompression algorithm but diff compression algorithm (similar to changing the level parameter). Ergo the sequences pointed to in the tabix index will have moved and thus doing a straight binary comparison of the two tabix files doesn’t tell us much. If you want to diff them you need something that understands the internals of tabix.

> On 20 Feb 2019, at 09:09, Michael R. Crusoe <notifications@github.com> wrote:
> 
> Here's the diff from running tabix on https://github.com/pysam-developers/pysam/blob/master/tests/tabix_data/example.gtf.gz
> 
> 6,10c6,10
> < 00000050: 6042 1803 17bf c580 0ab8 90d8 1fa5 2074  `B............ t
> < 00000060: cc3c 08fd 7219 84d6 dc06 a1fb b7a3 d27f  .<..r...........
> < 00000070: 7640 6874 3731 23f9 0366 6fb4 1684 0e81  v@ht71#..fo.....
> < 00000080: ba17 c667 6058 c6c7 80e4 5e98 7a98 b830  ...g`X....^.z..0
> < 00000090: 032a e041 3613 4a3b 4950 8746 b809 0200  .*.A6.J;IP.F....
> ---
> > 00000050: 6042 3207 267e 8b01 1570 21b1 3f4a 41e8  `B2.&~...p!.?JA.
> > 00000060: 9879 10fa e532 08ad b90d 42f7 6f47 a5ff  .y...2....B.oG..
> > 00000070: ec40 7523 cc0d cc48 fe80 d91b ad05 a143  .@u#...H.......C
> > 00000080: a0ee 85f1 1918 96f1 21bb 17a6 1e26 2e8c  ........!....&..
> > 00000090: e65e 1e64 33a1 b493 0475 6884 9b20 0000  .^.d3....uh.. ..
> (top is from a tabix compiled with libdeflate, bottom is without libdeflate)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mr-c** [comment] 2019-02-20 09:19
@mp15 Looks like our comments crossed each other. Indeed, after decompressing the contents of the datastreams are identical. I've updated the issue title to reflect this. Documentation on this fact will be helpful as some downstream users (pysam) are relying on the compression to always be byte-identical.

**Comment by jkbonfield** [comment] 2019-02-20 09:48
If it is uncompressed bit for bit identical then this is fine, provided the meta-data is valid.  For example I don't know if gunzip can uncompress both gzip (RFC1952) and deflate streams (RFC1951), but we shouldn't be switching from one format to another there.

Eyeballing your hexdump seems to imply neither are RFC1952 though; I assume raw deflate streams.  (I don't see the gzip ID1/ID2 header.)

**Comment by jkbonfield** [comment] 2019-02-20 09:50
For what it's worth, using libdeflate originally caused a number of failures in samtools/htslib tests too.  You need to be sure that you compare the uncompressed outputs in any binary tests as the implementation of deflate is irrelevant and not something mandated by the BAM spec.

You'd get likely these same failures if you ran using the Intel optimised gzip too.

**Comment by mr-c** [comment] 2019-02-20 11:02
Yes, you and I are highly aware how compilation settings and choice of library can affect things. Now lets be nice and add a note reminding others (or our future selves, should we forget) about this.

**Comment by jkbonfield** [comment] 2019-02-20 11:14
Apologies if I came over harsh at all in my comments.  It wasn't intended that way.

Anyway I'll close this issue as it's not a bug.

**Closed by jkbonfield** 2019-02-20 11:14 UTC
