### ISSUE TITLE
CRAM conversion : options store_nm and store_md 

### ISSUE THREAD

**Issue by JulieBlasquiz** [samtools/htslib#1827] opened 2024-08-21 10:09 UTC
Hello ,

I use samtools (version 1.3.1) to convert bam files into cram files.
I'd like to make sure that the MD and NM values are kept during conversion.
To do this, I use the option -O cram,store_md=1,store_nm=1 as mentioned in this documentation:
https://www.htslib.org/doc/samtools-view.html

Here's the complete command executed: 
samtools view -O cram,store_md=1,store_nm=1 -T hg19.fasta -o output.cram input.bam

I get the following message after executing the command: 
Unknown option 'store_md'

Which option should be used in version 1.3.1, equivalent to store_nm=1 and store_md=1?

Thanks for your help
Julie

**Comment by whitwham** [comment] 2024-08-21 10:23
Those options were not in 1.3.1 and you would need a newer version of samtools.  Version 1.3.1 was released eight years ago, there have been many improvements since then.

Is there a reason why you cannot use a modern version of samtools?

**Comment by jkbonfield** [comment] 2024-08-21 12:04
Our team doesn't support the Conda configuration, but there are some things you can try.

1. Use a new environment.  Conda dependency tracking is notorious for gradually breaking over time if you put everything in the same environment.  This is normally the cause of picking old versions of software.

2. Try using mamba instead of conda to install.  Although newer versions of the conda resolver incorporate the mamba technology, it's possible you don't have that version.

**Comment by JulieBlasquiz** [comment] 2024-08-21 13:10
I followed your advice : 

Created a new env : `conda create -n Samtools_1.20`
Configuration with : `conda config --add channels bioconda`
Then install samtools with :  `conda install -c bioconda samtools=1.20`

The samtools command now executes as expected

Many thanks !

**Comment by jkbonfield** [comment] 2024-08-21 15:21
Great.  Closing this as resolved then.

**Closed by jkbonfield** 2024-08-21 15:21 UTC
