### ISSUE TITLE
"samtools index <cram>" hangs populating the REF_CACHE

### ISSUE THREAD

**Issue by mbookman** [samtools/htslib#412] opened 2016-09-14 17:57 UTC
Have been finding that running `samtools index` on a CRAM file will periodically hang while it is populating the REF_CACHE. With certain tests at scale, it occurred 10-20% of the time. The hang did not resolve itself; on a few occasions I left the process run for a couple of days without it ever completing (on success it would finish in ~ 10 minutes).

I ran [strace](http://linux.die.net/man/1/strace) on the command, capturing the output to a file:

`strace samtools index NA12878.cram &> ./strace.txt`

Looking at the end of the strace log for a hung instance of `samtools index`, I see:

```
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 5
setsockopt(5, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
setsockopt(5, SOL_SOCKET, SO_LINGER, {onoff=0, linger=0}, 8) = 0
connect(5, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("193.62.193.80")}, 16) = 0
write(5, "GET /ena/cram/md5/378e070f5556e2"..., 101) = 101
read(5, 
```

I put 193.62.193.80 into my browser and it returns:

> ves-pg-12.ebi.ac.uk

That led me to the samtools documentation on populating the REF_CACHE. It also led me to:

[[Meta] Travis appears to hang on CRAM tests](https://github.com/samtools/samtools/issues/279)

This describes the same issue, and it is noted:

> The EBI reference server is just too unreliable to use at present.
> (It's the Achilles heel of CRAM alas.)

[Tests were updated](https://github.com/samtools/htslib/commit/1903fd40e65927df998700fc1276d9bd1165ee34) to avoid the dependency on EBI and [docs](http://www.htslib.org/workflow/#the-refpath-and-refcache) were updated:

> While the EBI have an MD5 reference server for downloading reference sequences over http, we recommend use of a local MD5 cache. We have provided with Samtools a basic script (misc/seq_cache_populate.pl) to convert your local yeast.fasta to a directory tree of reference sequence MD5 sums:

This definitely seems like a best practice to avoid repeatedly fetching static reference information from the EBI server which, as in this case, will frequently be used locally over and over again.

However it would be good if the code that fetches the sequence information had a timeout and retry mechanism, as the EBI server does not appear to timeout the connection. The client code could be more defensive.

I believe the code path in question here is:

[static int cram_populate_ref(cram_fd *fd, int id, ref_entry *r) {](https://github.com/samtools/htslib/blob/503b09d6a0e81b771997782ef87ab39a4bb51618/cram/cram_io.c#L2180)
-> [mFILE *open_path_mfile(char *file, char *path, char *relative_to) {](https://github.com/samtools/htslib/blob/abfd337122753870274cb5ed6163ec536e21c9a9/cram/open_trace_file.c#L307)
->-> [mFILE *find_file_url(char *file, char *url) {](https://github.com/samtools/htslib/blob/abfd337122753870274cb5ed6163ec536e21c9a9/cram/open_trace_file.c#L166)
->->->   [hread(hFILE *fp, void *buffer, size_t nbytes)](https://github.com/samtools/htslib/blob/abfd337122753870274cb5ed6163ec536e21c9a9/cram/open_trace_file.c#L188)
->->->-> [ssize_t hread2(hFILE *fp, void *destv, size_t nbytes, size_t nread)](https://github.com/samtools/htslib/blob/74bcfd7c28fbdd041dad790a43041f80681c613b/hfile.c#L230)

which ultimately blocks here:

[ssize_t n = fp->backend->read(fp, dest, nbytes);](https://github.com/samtools/htslib/blob/74bcfd7c28fbdd041dad790a43041f80681c613b/hfile.c#L238)

Could the [hFILE_backend struct](https://github.com/samtools/htslib/blob/74bcfd7c28fbdd041dad790a43041f80681c613b/hfile_internal.h#L34) include a `select` method so that hread2 can [select](http://linux.die.net/man/2/select) on the socket before trying to read from it?

It could `select` with a timeout, enabling calling code to close the connection and retry.

Also - it would be great if this message were enhanced:

> Creating reference cache directory /root/.cache/hts-ref
> This may become large; see the samtools(1) manual page REF_CACHE discussion

to include something _like_:

> Creating reference cache directory  /root/.cache/hts-ref from http://www.ebi.ac.uk:80
> This may become large and place heavy load on the remote servers.
> Pre-populating this cache is recommended; see the samtools(1) manual page REF_CACHE discussion

Seeing something like this would have given me more clues that the cache was being populated from a remote server, along with more of a call to action.

Thanks!

**Comment by jkbonfield** [comment] 2017-02-07 12:41
Sorry I missed this before.

Does this still happen if you use libcurl as the networking backend instead of knet? (Ie with ```./configure --enable-libcurl```).  I haven't looked into the code in detail, but a cursory glance shows it has some code dealing with timeouts in there so possibly it's already fixed.  (I'm somewhat disinclined to modify knet given it's a third party library.)

Also, have you reported this problem to the EBI?  10-20% hangup is appalling and most probably something is amiss at their end if it still fails like that.

**Comment by jkbonfield** [comment] 2017-03-07 15:28
Closing as no confirmation on the bug existing with libcurl and unable to reproduce locally.

If you find this issue is still there when using libcurl then please comment and I'll reopen the issue.  Thanks.

**Closed by jkbonfield** 2017-03-07 15:28 UTC
