### ISSUE TITLE
Unaligned cram conversion error

### ISSUE THREAD

**Issue by jts** [samtools/htslib#1005] opened 2019-12-12 14:49 UTC
Hi,

I'm trying to repack a cram file to have fewer sequences per slice following a discussion with @jkbonfield on twitter. The input is an unaligned cram file containing ONT signal data that I downloaded from the ENA. 

Samtools/htslib version info:

```
Version: 1.10-2-gc62a0f1 (using htslib 1.10-1-g5e7b76b-dirty)
```

Steps to reproduce:

```
wget ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram
samtools view -O cram -o test.cram nc-RNAs_DKC1_WT_1.cram
```

Error:
```
[E::cram_get_ref] Failed to populate reference for id 0
[main_samview] failed to write the SAM header
```

If I change -O to `sam` or `bam` the file conversion works.

**Comment by jkbonfield** [comment] 2019-12-13 09:42
**Ugh!  The header is borked**.  It's illegal SAM (starts with a char not in the permitted regexp) and doubly so for CRAM (has no associated M5 tag).

```
@SQ	SN:*	LN:0
```

This looks to have been a case of https://github.com/EGA-archive/ont2cram/issues/16, now fixed, escaping into the wild. :-(

There's one sensible fix and two ghastly workarounds:

1. Reheader the flle.  It can be done in streaming mode as part of the file rewriting.

```
samtools view -H ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram| egrep -v '^@SQ' > _hdr
samtools reheader -P _hdr ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram | samtools view -O cram,seqs_per_slice=???? -o out.cram
```

2. Turn on "no_ref" mode so it doesn't attempt to process the SQ records and create M5 tags for the header.  This worjks, but you'll get the same problem when reading the file back and so you need to keep continually using "no_ref" opt.

```
samtools view -O cram,seqs_per_slice=1000,no_ref ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram -o out.cram
```

3. "Credit" to David Jackson for this one ;-).  Create a star.fa containing the "*" empty seq!  I failed to get that working (and infact managed to coredump faidx - win!), but it's perhaps doable.  It suffers with the same problem as option 2 though that you'd need to keep the fake ref around.


Also, you may wish to explore the `bases_per_slice` parameter instead of `seqs_per_slice` if you have highly variable sequence lengths. Eg:

```
samtools reheader -P _hdr ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram|samtools view -O cram,bases_per_slice=500000 -o out.cram
```

By default it sets bases per slice to be 300 * seqs per slice, so it's not a limit on Illumina data but does prevent long read technologies from creating huge slices.

Finally as a "work in progress" update, I have a CRAM4 branch which uses a DELTA transform to more efficiently encode the ONT signal data.  It's not ready yet, but an example on this data:

```
-rw-r--r-- 1 jkb team117 116682863 Dec 13 09:38 out3.cram
-rw-r--r-- 1 jkb team117  91238105 Dec 13 09:39 out4.cram
```

**Comment by valeriuo** [comment] 2019-12-13 09:51
Also, running 
```
samtools view  ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram | cut -f1-8 | head -20
@8f579cd3-e52c-4492-be12-9e173001bffe   4       *       1       0       *       *       1
@aed06966-a534-4ac2-9445-5f21c57513bb   4       *       1       0       *       *       1
@31e11c32-6e66-4280-a317-e6fd1bc72f91   4       *       1       0       *       *       1
@390d4737-dfd7-450d-b42c-4c65ae4c2cd5   4       *       1       0       *       *       1
@b5b2cd56-11f5-40bf-9c19-b9c2e6107094   4       *       1       0       *       *       1
@2b474c08-c985-4b81-8811-bebe30fa4866   4       *       1       0       *       *       1
@b9b6e64f-6a5f-4cb0-a9a6-12b074ce795b   4       *       1       0       *       *       1
@25546e08-7700-4989-8762-9a08645d9738   4       *       1       0       *       *       1
@5ca0912b-53b5-4a61-95ec-df766c16671e   4       *       1       0       *       *       1
@ff0b6aad-61e9-483b-ba95-752f8bc60acf   4       *       1       0       *       *       1
@84937854-2475-45b6-9e63-1275c2735d9c   4       *       1       0       *       *       1
@e345f96f-53f6-4a24-a17c-d83dbb65d3f0   4       *       1       0       *       *       1
@f4fa783c-5f76-4636-bb2b-d48fe2f0c597   4       *       1       0       *       *       1
@7d038ac7-dbb5-45fb-b93d-687098bca85a   4       *       1       0       *       *       1
@ed6fe0a6-ffea-4997-8d46-556aa597bb2e   4       *       1       0       *       *       1
@685b2bad-fa8d-4243-b23c-408144da24cb   4       *       1       0       *       *       1
@92412292-8d82-4cc7-9160-e56c13932358   4       *       1       0       *       *       1
@4a119180-0302-4aac-8da8-3dc6891b82c2   4       *       1       0       *       *       1
@82b8c3a5-445e-45a5-9411-b6861367d84e   4       *       1       0       *       *       1
@ae73dc17-7251-42ed-8847-dbfde74e064d   4       *       1       0       *       *       1
```
shows the read names starting with `@`, which is explicitly forbidden by the standard.

> Header lines start with `@', while alignment lines do not.

How was this file produced?

**Comment by jkbonfield** [comment] 2019-12-13 09:57
Oops there are more horrors.  The read names are invalid too.  Eg:

```
@8f579cd3-e52c-4492-be12-9e173001bffe   4       *       1       0       *       *       1       0       NGGGGCCACGAGCNGAGNGCGNCCNGNCACNCCACNCCCANGNCCCNNGGG...
```

All this data really needs reprocessing and uploading in a corrected form.

I assume this has been directly lifted from the first the first line of the fastq file without removing the header letter.  I'm somewhat surprised samtools is happy to swallow this.

To fix this you'd need an inline edit, eg view to SAM, sed, and view back to CRAM.

**Comment by valeriuo** [comment] 2019-12-13 10:11
> I'm somewhat surprised samtools is happy to swallow this.

It only works with CRAM, because the header is kept in a separate data block. Once you go to SAM or BAM the errors start popping up:

```
samtools view nc-RNAs_DKC1_WT_1.sam
[E::sam_hrecs_error] Header line does not have a two character key at line 55: "@8f579cd3-e52c-4492-be12-9e173001bffe   4       *       1       0       *       *       1       0 
```

**Comment by jkbonfield** [comment] 2019-12-13 10:26
Maybe this suffices:

```
samtools view -H ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram| egrep -v '^@SQ' > _hdr
samtools reheader -P _hdr ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR370/ERR3700282/nc-RNAs_DKC1_WT_1.cram | samtools view -h | sed 's/^@\([a-z0-9-][a-z0-9-]*\)/\1/' | samtools view -O cram,seqs_per_slice=1000 -o out.cram
```

**Comment by jts** [comment] 2019-12-13 14:05
Thanks guys, I'll fix this locally with reheader so I can carry on trying to build a read-based index. 

Pinging @a-slide so he's aware of the issues with the files he sent to the ENA so they can be fixed.

**Comment by jkbonfield** [comment] 2020-01-07 17:08
Closing as issue was caused by invalid data.

**Closed by jkbonfield** 2020-01-07 17:08 UTC
