### ISSUE TITLE
libcurl enabled applied by default?

### ISSUE THREAD

**Issue by mkirsche** [samtools/htslib#1261] opened 2021-03-30 15:07 UTC
Hi,

I just tried to install htslib on a system without libcurl with the following commands: 

```
./configure --prefix=/path/to/htslib --without-libdeflate --disable-bz2
make
make install
```

However I got this error:  `hfile_libcurl.c:47:10: fatal error: curl/curl.h: No such file or directory`

I was eventually able to install it by adding the command line flag `--disable-libcurl`, but this option is not listed in the documentation as far as I could see (and the INSTALL document implies that libcurl is disabled by default since it is listed as an optional dependency), so I had to guess that it existed based on similar command line flags for other dependencies.  Could you please update either the documentation or the default behavior?

Thanks!
Melanie

**Comment by jkbonfield** [comment] 2021-03-30 15:27
This is also a bug of the configure script apparently.  It's meant to spot if it doesn't have curl and build without it automatically.  It looks like it only tests against run-time install rather than a compile-time one so it won't spot missing headers.

Note your best solution though is to install the recommended dependencies. Eg from INSTALL:

```
Debian / Ubuntu
---------------

sudo apt-get update  # Ensure the package list is up to date
sudo apt-get install autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev

Note: libcurl4-openssl-dev can be used as an alternative to libcurl4-gnutls-dev.
```

**Comment by jmarshall** [comment] 2021-03-31 08:47
When I tried to reproduce this, it **did** spot that it didn't have curl and built without it automatically; see also #1177.

So it would be good to know what version you were trying to build (were you starting from an _htslib-X.Y.tar.bz2_ tarball?), what operating system you're on, what output from `./configure …` you got, and perhaps to attach the resulting _config.log_.

**Comment by jmarshall** [comment] 2021-03-31 15:57
> It looks like it only tests against run-time install rather than a compile-time one

For libcurl it checks `AC_CHECK_LIB([curl], [curl_easy_pause], …)`, which is the standard autoconf way to check for a compile-time-available library function. This tries to link against `-lcurl`, which will succeed if _libcurl.so_ is present (which is supplied by the libcurl-devel package) but not if only _libcurl.so.4_ is present (which is supplied by the libcurl runtime package). So this test too is checking the compile-time capabilities.

For the other libraries used, it checks the equivalent of `AC_CHECK_HEADERS([curl/curl.h], …)` followed by `AC_CHECK_LIB([curl], [curl_easy_pause], …)`. This is mostly just for exhaustiveness and debugging clarity — you get shown which of the header and/or the library is the problem — and shouldn't in general make a difference to whether the checking succeeds overall or not. However there's no reason for the libcurl check not to work similarly, so this small oversight might as well be corrected.

If @mkirsche has really found a scenario in which this would make a difference — i.e., _libcurl.so_ is present and can be linked against but _curl/curl.h_ is not present — that would be rather interesting :smile:. So far htslib has only seen that once, for _liblzma.dylib_, which lead to https://github.com/samtools/htslib/pull/628#issuecomment-345982008.

**Comment by mkirsche** [comment] 2021-03-31 15:58
Thank you for looking into this so quickly

Here's the output from `./configure ...`

```
ux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/gcc accepts -g... yes
checking for /data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for grep that handles long lines and -e... /usr/bin/grep
checking for C compiler warning flags... -Wall
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking shared library type for unknown-Linux... plain .so
checking whether the compiler accepts -fvisibility=hidden... yes
checking how to run the C preprocessor... /data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for fsync... yes
checking for drand48... yes
checking for srand48_deterministic... no
checking whether fdatasync is declared... yes
checking for fdatasync... yes
checking for library containing log... -lm
checking for zlib.h... yes
checking for inflate in -lz... yes
checking for library containing recv... none required
checking for lzma.h... yes
checking for lzma_easy_buffer_encode in -llzma... yes
checking whether htscodecs files are present... yes
checking for curl_easy_pause in -lcurl... yes
checking for CCHmac... no
checking for library containing HMAC... -lcrypto
checking for library containing regcomp... none required
checking whether PTHREAD_MUTEX_RECURSIVE is declared... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating htscodecs.mk
config.status: creating htslib.pc.tmp
config.status: creating config.h
```

And here's the output of `lsb_release -a`

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 8.1.1911 (Core) 
Release:	8.1.1911
Codename:	Core
```

I've also attached the config.log file.  Please let me know if there's anything else I can provide!

Thanks!
Melanie

[config.log](https://github.com/samtools/htslib/files/6237812/config.log)

**Comment by jmarshall** [comment] 2021-03-31 16:53
Your environment is fairly astonishing…

```
checking for gcc... /data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/gcc

# From config.log
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/scratch4/mschatz1/mkirsche/anaconda3/lib -Wl,-rpath-link,/scratch4/mschatz1/mkirsche/anaconda3/lib -L/scratch4/mschatz1/mkirsche/anaconda3/lib'
```

So you are using a GCC installed via Spack into a surprising path (but I am not familiar with Spack), and you may well be using a libcurl that you have installed yourself via anaconda.

If this guess about an anaconda libcurl is correct, then the problem is that you have exported a `$LDFLAGS` environment variable that supplies a `-L` option to make linking work, but you have not exported a `$CPPFLAGS` environment variable containing a similar `-I` option.

So you should probably review your Spack GCC installation and review whatever script is setting up this `$LDFLAGS` environment variable (and review whether there is anything that is subsequently unsetting `$CPPFLAGS` and/or `$CFLAGS`).

(If you are using anaconda anyway, have you considered installing htslib via anaconda too, rather than building it yourself?)

**Comment by mkirsche** [comment] 2021-03-31 19:26
That's really interesting - since it's a shared server I'm not aware of how the setup was done, so I never realized it was so non-standard.

I'm pretty sure the libcurl issue is unrelated to anaconda - I still get the exact same issue when I deactivate my conda environment (as well as the conda base environment).  I'd be happy to send the logs from that build attempt too if they would be more informative.

And yes, I've used htslib through anaconda a number of times with no issues, and that's what I usually do for running it standalone.  However, I was running another program which uses htslib as a submodule (https://github.com/GrandOmics/svmerge) and wasn't sure if that was possible through the conda version.

**Comment by jmarshall** [comment] 2021-04-01 12:50
The log at the moment doesn't explain why it's able to say `yes` to `checking for curl_easy_pause in -lcurl`. So probably the most informative log would be _config.log_ from running

    ./configure CFLAGS=-Wl,--print-map […your other configure options…]

in your current conda environment activated setup. And separately also the same thing with conda deactivated.

This is the sort of thing that's very hard to track down from afar. So if the person who set up the shared server is still around, it's probably time to seek their assistance. :smile:

The bioconda htslib package installs the header files etc. So svmerge will probably need a bit of hacking of its build infrastructure to use an external htslib, but you'd be able to build it with the conda htslib about equally as easily as with one you've built yourself.

**Comment by mkirsche** [comment] 2021-04-01 17:24
I've attached the log files with the additional CFLAGS argument with and without the conda environment activated.

And that's good to know about the bioconda package! I managed to get it working with building from source by just adding --disable-libcurl - as someone who doesn't develop in C++ I preferred to avoid changing the build infrastructure if at all possible, and it looks like the only use of the htslib library svmerge depended on was reading VCF files so I didn't think libcurl would be necessary.  But I'll definitely keep that in mind in case I run into similar issues in the future.

[config_conda.log](https://github.com/samtools/htslib/files/6245292/config_conda.log)
[config_no_conda.log](https://github.com/samtools/htslib/files/6245293/config_no_conda.log)

**Comment by daviesrob** [comment] 2021-04-01 17:34
Both your log files say:
```
LOAD /scratch4/mschatz1/mkirsche/anaconda3/lib/libcurl.so
```

Judging from this, and other anaconda mentions in the file, it looks like you haven't managed to get rid of the environment completely.

**Comment by mkirsche** [comment] 2021-04-01 18:03
Oh, it looks like some of the conda environment variables were persisting even after running `conda deactivate`.  I just tried again in a new session after disabling the base environment from being activated in my .bash_rc and it works fine (by detecting that libcurl is not present).  So it appears to be a conda-related issue.

Here's the setup of the libcurl files in my anaconda3/lib folder:

```
libcurl.so -> libcurl.so.4.6.0
libcurl.so.4 -> libcurl.so.4.6.0
libcurl.so.4.6.0
```

The conda environment I've been working in doesn't have any additional software installed (I just did `conda create -n test` and then `conda activate`) - here's the output of `conda env export`:

```
name: test
channels:
  - defaults
prefix: /scratch4/mschatz1/mkirsche/anaconda3/envs/test
```

So it seems like the lib folder is shared by all environments, and that maybe the libcurl.so files have a weird setup from installing libcurl through conda in one or more other environments?

**Comment by jmarshall** [comment] 2021-04-01 19:24
That arrangement of _libcurl.so*_ symlinks is normal for a curl installation (whether via conda or CentOS packages or any other method), and the _/scratch4/mschatz1/mkirsche/anaconda3/lib_ directory is the _lib_ subdirectory of your base conda environment.

Those `LOAD` log lines noted by @daviesrob indicate that my earlier guess was correct: the _libcurl.so_ from the libcurl conda package installed in your base environment is being used, independent of `conda activate`/ `deactivate`. It seems like something alongside your conda enabling stuff in _.bashrc_ is exporting a conda-esque `$LDFLAGS` setting that's unaffected by which environment you have activated. So you could add a similar environment variable pointing to the header files:

    export CPPFLAGS=-I/scratch4/mschatz1/mkirsche/anaconda3/include

and then run `./configure …` or conversely you could `unset LDFLAGS` or track down the “something”.

Anyway, htslib should probably add a line to _configure.ac_ as per https://github.com/samtools/htslib/issues/1261#issuecomment-811178454 to aid debugging scenarios like yours in which _curl/curl.h_ is present but not discoverable by the compiler. And glancing at svmerge it looks like you're absolutely right that a `--disable-libcurl` build will suffice for its needs anyway.

**Comment by mkirsche** [comment] 2021-04-01 19:46
Yeah, it looks like the issue is that when I activate a non-base conda environment, the LDFLAGS from the base environment persists but not the CPPFLAGS.

```
(base) ]$ echo $LDFLAGS
-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/scratch4/mschatz1/mkirsche/anaconda3/lib -Wl,-rpath-link,/scratch4/mschatz1/mkirsche/anaconda3/lib -L/scratch4/mschatz1/mkirsche/anaconda3/lib
(base) $ echo $CPPFLAGS
-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /scratch4/mschatz1/mkirsche/anaconda3/include
(base) $ conda activate test
(test) $ echo $LDFLAGS
-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/scratch4/mschatz1/mkirsche/anaconda3/lib -Wl,-rpath-link,/scratch4/mschatz1/mkirsche/anaconda3/lib -L/scratch4/mschatz1/mkirsche/anaconda3/lib
(test) $ echo $CPPFLAGS

(test) $
```

So in any case that appears to be an issue with how conda is handling these environment.  And the fact that they persist after deactivation is apparently a known issue already (https://github.com/conda/conda/issues/10195), so that's what was causing it to be permanently set when my bashrc activated the base environment.

And thanks for checking on the validity of using disable-libcurl in this situation.  It felt a little questionable to use it given that there's no documentation for the flag and I just happened to stumble upon its existence, so I really appreciate the stamp of approval from someone who understands it better.

**Comment by jmarshall** [comment] 2021-04-01 21:25
Nice find — I would not have guessed that this would be so broken in conda. (Although I was unable to reproduce it in my conda installation, so there may be some dependence on versions and packages installed :shrug:.)

The pairing of `--enable-foo`/`--disable-foo` and `--with-bar`/`--without-bar` options is obliquely described in `./configure --help`, but it seems people are just supposed to already know about it… HTSlib's _INSTALL_ should probably mention that each pair exists and that the one that's described in the list of configure options is the **non-default** configuration of each pair and in general you can always use the other one to explicitly switch things off (or on, when `--disable-whatever` is the one listed). I thought there was wording in the [standard generic install instructions](http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob;f=doc/install.texi;h=3bedb4efcee4cea83e88486d576c19131d00e104;hb=HEAD#l222) to copy, but they don't seem to mention this either.

**Comment by valeriuo** [comment] 2021-06-16 11:54
Fixed by https://github.com/samtools/htslib/pull/1265

**Closed by valeriuo** 2021-06-16 11:54 UTC
