### ISSUE TITLE
lzma, bz2 dependency

### ISSUE THREAD

**Issue by willmclaren** [samtools/htslib#490] opened 2017-03-14 11:04 UTC
Does support for lzma and bz2 have to be on by default?

Adding these dependencies has broken a *lot* of Ensembl's installation code and Travis and Docker builds.

It appears the fix is not a simple one, as we are now required to run `autoheader` and `autoconf`, which are not default packages in many setups, before running `./configure` and then `make`. 

Previously you could `git clone`, `make` and be off and running.

htslib has gained so much traction partly because of its simplicity, ease of installation and lack of external dependencies.

**Comment by lairdm** [comment] 2017-03-14 11:54
I've just checked and this issue would be solved by the maintainers running autoreconf and including aclocal.m4, config.h.in, and configure with the distro. It's been far too many years since I've played with the auto* tool chain, but these scripts and templates are usually included in a package and would allow users to simply ./configure the package to build it without the auto* steps first. I already have a fork of the repo which I'm not ready to merge back so I can't quickly make this change and do a PR, but if anyone else wanted to quickly do this change it'd solve/simplify part of the build issue quite quickly.

**Comment by mp15** [comment] 2017-03-14 11:54
I have tested on Ubuntu Precise (coming up to 5 years old) and you can still git clone and make and be off and running. Could you be a bit more specific about your configuration so we know what the problem is? You still don't have to run configure unless you want to disable our default dependancies (zlib, lzma, bz2 and curses) or to enable libcurl (recommended) or s3 support. I know Ensembl has a lot of older boxes, but none of them are due to live past April AFAIK?

As for LZMA and bz2 they are required for CRAM decoding, if you don't have them you simply cannot decode a lot of the CRAMs out there. We do not want to put out a library which cannot do the task it is designed for by default. Given that they're installed by default on most distributions which are still within the security support window I would be inclined to say is is fair to assume that -llzma and -lbz2 will work in 95% of cases (sadly not xz on OS X but meh).

**Comment by willmclaren** [comment] 2017-03-14 12:05
@mp15 the issue is not so much users' systems as Travis and the like. See this failed build as an example:

https://travis-ci.org/Ensembl/ensembl-variation/jobs/210885028

It's based on Precise too. This will also happen to anything else using a bare-bones virtualised environment, such as Docker.

We've reverted to using 1.3.2 for now (though there will probably be some places we miss this change and still get bitten).

I guess we shouldn't have been depending on master/develop retaining the same set of dependencies in the first place.

**Comment by jkbonfield** [comment] 2017-03-14 12:11
Fixing travis is trivial.  See https://github.com/samtools/htslib/blob/develop/.travis.yml for an example of how to install the dependencies on linux and macosx systems, specifically lines 16-26.

There are ways to disable lzma/bzip if you use the configure script (really it's just one extra command line - configure+make instead of make), but whether this is appropriate depends on what you are using these tools for.  If you're only dealing with BAM and not CRAM then it's appropriate, but otherwise I'd say not.

So far I think most CRAM files don't use bzip2 or lzma simply because while Java Cramtools and C Scramble have supported these codecs for a couple years (and they're in the CRAM specification), htslib hasn't been able to cope so we have deliberately avoided generating data files that would break samtools.  This may change soon!

**Comment by jkbonfield** [comment] 2017-03-14 12:21
@lairdm  

> I've just checked and this issue would be solved by the maintainers running autoreconf and including aclocal.m4, config.h.in, and configure with the distro. 

This is already true for the distributed tar files.  However we don't put (usually) auto-generated files in the git repository as it is a pain when you get git conflicts just because you ran a different version of autoconf or built on a different system.  Perhaps you should consider pulling in the releases instead of doing raw git clones.

**Comment by willmclaren** [comment] 2017-03-14 12:42
@jkbonfield it's more the fact we have 6 repositories (that I know of) that depend on htslib, all using the same recipe, and this change came at a bad time in our release cycle (which of course is not your concern).

**Comment by jkbonfield** [comment] 2017-03-20 09:42
The only reasonable way to avoid the dependency IMO is to have a switch to completely disable CRAM support.  I do not particularly like the current ability to compile htslib with a subset of the CRAM format (by disabling these libraries) as it's just a recipe for more support queries "why does htslib not work with my CRAM file?", but historically it's been how CRAM in htslib worked.

For now though, I'm closing this issue to tidy things up a bit as it's not really an issue with htslib given there are several solutions.  Our recommendation is to either add the dependencies to your build setup or to use the configure script to disable them.  If using the latter route, avoid the autotools dependencies by pulling down the release tarballs instead of cloning from git.

**Closed by jkbonfield** 2017-03-20 09:42 UTC
Labels: needs-feedback, question

**Comment by kemin711** [comment] 2018-05-04 19:30
I had not problem with bz2 and lzma on ubuntu.  But on centos, htslib could not find them. They are the system /usr/include and /usr/lib64 on centos.  And I also put one latest version, compiled with the latest compiler (gcc 6.3.0) in the prefix directory.  I tried autoreconf -if after adding the $LDFLAGS="$LDFLAGS -L$prefix/lib" and $CPPLAGS="$CPPFLAGS -I$prefix/include"
Just before the test for bz2 in the configue.ac file.  I agree I did not try hard enough.  Anyone had a suggestion for how to fix this build bug?

**Comment by jkbonfield** [comment] 2018-05-08 08:03
It does sound like a bug in our configure script then.  We shouldn't *need* to specify rpath either for compilation, although it has some use when running programs to avoid needing to set LD_LIBRARY_PATH instead.

We'll get a Centos 7 image to experiment on, if we don't have one set up already.  It's a pain that centos uses a different library location, but that should be our problem - not yours.

**Comment by daviesrob** [comment] 2018-05-08 13:59
@kemin711 The problem is likely due to **development** packages not being installed on centos.  Also if you try to build and install `libbz2` yourself you don't get a usable library (the shared one isn't installed and the static one is not built with `-fPIC`).  So you either need to install `bzip2-devel` **or** build `libbz2` with `make CFLAGS='-g -O2 -fPIC -D_FILE_OFFSET_BITS=64'` **or** build `libbz2` using `make -f Makefile-libbz2_so` and then install the shared libraries yourself.

Please see https://github.com/samtools/htslib/issues/696#issuecomment-387405020 for recipes that should work on centos.
