### ISSUE TITLE
Building outside source directory fails

### ISSUE THREAD

**Issue by paulmenzel** [samtools/htslib#1269] opened 2021-04-12 14:17 UTC
Creating a build directory, calling configure from it, doesn’t create create a Makefile inside the build directory.

    $ mkdir /dev/shm/build
    $ cd /dev/shm/build
    $ /dev/shm/htslib-1.12-0/source/configure --prefix=/scratch/local2/TOOLS --bindir=/scratch/local2/TOOLS/bin --sbindir=/scratch/local2/TOOLS/sbin --libexecdir=/scratch/local2/TOOLS/libexec --sysconfdir=/scratch/local2/TOOLS/etc --sharedstatedir=/scratch/local2/TOOLS/var --localstatedir=/scratch/local2/TOOLS/var --libdir=/scratch/local2/TOOLS/lib --includedir=/scratch/local2/TOOLS/include --datarootdir=/scratch/local2/TOOLS/share --datadir=/scratch/local2/TOOLS/share --infodir=/scratch/local2/TOOLS/share/info --localedir=/scratch/local2/TOOLS/share/locale --mandir=/scratch/local2/TOOLS/share/man --docdir=/scratch/local2/TOOLS/share/doc/htslib --exec-prefix=/scratch/local2/TOOLS

Building outside the source directory is good practice to leave it untouched.

**Comment by jkbonfield** [comment] 2021-04-12 14:44
Agreed, however unfortunately this isn't supported by the Htslib/Samtools/Bcftools build system.

The INSTALL notes don't explicitly state it isn't supported, which perhaps they should, but neither does it mention that you can and the instructions for building do not make a sub-directory.

**Comment by paulmenzel** [comment] 2021-04-12 14:50
As you use GNU Autotools, it should be easily supported by using the correct variables.

1.   https://www.howtobuildsoftware.com/index.php/how-do/bIOX/autotools-autoconf-libtool-autotools-top-srcdir-and-abs-top-srcdir-are-empty
2.  https://events.static.linuxfound.org/sites/events/files/slides/petazzoni-autotools-tutorial.pdf

**Comment by jmarshall** [comment] 2021-04-12 14:55
This is a duplicate of #231. Htslib/samtools/bcftools use autoconf, but in a somewhat unorthodox way which means that this is nontrivial. I have an old draft for doing out-of-tree builds for htslib which should perhaps be dusted off, but because of the unified build it's much harder for the other two (hence there's been little motivation to do it for htslib either).

**Comment by jkbonfield** [comment] 2021-04-12 15:09
We could ignore the unified build and just require a make install first.  Ie samtools needs htslib building (out of tree if desired) and installing, before doing `/path/to/source/configure --with-htslib=/install/root`.

Although that said, if we have out of tree htslib builds working, then maybe it's just a matter of making an htslib subdir of our out-of-tree samtools build and configuring htslib (out of tree) there.  Hard to say until we try.  I'm probably missing something. :)

**Comment by daviesrob** [comment] 2021-04-13 13:34
Closing as a duplicate of #231.  Agreed it would be useful if just for HTSlib.

**Closed by daviesrob** 2021-04-13 13:34 UTC
