### ISSUE TITLE
FASTA indexing broken in Windows

### ISSUE THREAD

**Issue by teepean** [samtools/htslib#866] opened 2019-05-01 11:11 UTC
I have been trying to get mpileup (both samtools and bcftools) working on Windows but run in to following error:

`[E::fai_retrieve] Failed to retrieve block. (Seeking in a compressed, .gzi unindexed, file?)`

After investigating the issue I noticed that faidx produces a broken fa index. For example hg19.fa that I use has the following in hg19.fa.fai

`chr6	171115067	2312510653	50	51`

But when indexed with samtools 1.6 to 1.9 I get:

`chr6	171115067	18446744071727094973	50	51`

I haven't been able to debug how the index is being read but I assume that it is broken in similar fashion.

I did test an older binary (samtools-0.1.12a_i386-win32) and that produces a correct index and can read an indexed fasta even if it was produced on Linux.

I have used latest MSYS2 with gcc 8.3.0 and clang 8.0.0. I have several compiled versions of samtools 1.9 created with different versions of gcc and none of them work.

EDIT: I tested with compressed hg19.fa and now it just stops without an error message after chromosome 5.

**Comment by valeriuo** [comment] 2019-05-01 14:49
The erroneous value is caused by the fact that `long` is a 32 bit signed type on [Windows](https://docs.microsoft.com/en-us/windows/desktop/WinProg/windows-data-types), while on Linux is 64 bit long. A fix is in the making.

**Comment by teepean** [comment] 2019-05-01 15:26
Thank you!

**Closed** 2019-05-09 10:34 UTC
