### ISSUE TITLE
Tabix Returns Empty from AWS S3

### ISSUE THREAD

**Issue by valenciacristian** [samtools/htslib#872] opened 2019-05-14 15:00 UTC
Hello, I am trying to pull portions of standard VCFs that are stored in our AWS S3 buckets. The first file I pull always works, but subsequent files return empty. Am I doing something wrong?

Here is an example of my code:
`tabix s3://<bucket and path>final.vcf.bgz Chr1 > <destination>.vcf.gz`

If I run that command more than once, the rest of the files will be empty

**Comment by valeriuo** [comment] 2019-05-14 15:05
Duplicate of #763

**Comment by valeriuo** [comment] 2019-05-16 14:43
Did you verify that the other files have the reference you are filtering by? Any errors reported?

**Comment by daviesrob** [comment] 2019-05-21 15:22
Do your vcf files all have the same name, but different paths?

HTSlib downloads the index and stores it locally with the same name as the remote file.  This can cause problems if the files at the remote end all have the same name, as it will use the one it downloaded previously which will be for the wrong vcf file.

**Comment by valeriuo** [comment] 2019-07-01 10:11
Fixed by #870

**Closed by valeriuo** 2019-07-01 10:11 UTC
